### ISSUE TITLE
Move install docs to doc website

### ISSUE THREAD

**Issue by dharhas** [Quansight/qhub-terraform-modules#5]
Move docs from : 

https://github.com/quansight/qhub-home
https://github.com/Quansight/qhub-ops/tree/master/qhub_ops/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/docs

to

https://qhub.readthedocs.io/en/latest/

may need to remove cookie cutter components

**Comment by tonyfast** [comment]
this is finished and update in master on qhub-home
