### ISSUE TITLE
Versioning modules against qhub needs more thought

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub-terraform-modules#53]
The default behavior of qhub is to use modules from qhub-terraform-modules main branch.

But for a fixed install of qhub (e.g. 0.3) this main branch may change over time as more releases happen, and could become incompatible.

Certainly, if we use GitLab Flow on this repo, so main is the active development branch, this is very dangerous.

It could make sense for qhub to default to a tag named after the qhub version (e.g. 0.3), and we therefore need to tag/release qhub-terraform-modules immediately before any qhub release.

**Comment by danlester** [comment]
Actually, does it make sense to publish these as official qhub modules in the Terraform registry?

**Comment by leej3** [comment]
Would this be solved by tracking the qhub-terraform-modules repo as a submodule of qhub-cloud? That will make the modules' version explicit across branches/versions.

**Comment by costrouc** [comment]
The current solution I've been doing is to create a branch on `qhub-terraform-modules` e.g. `release-0.3.2` and then pinning the qhub release to use this branch see https://github.com/Quansight/qhub/blob/release-0.3.2/qhub/template/cookiecutter.json#L16. This should allow us to "upstream" module fixes to older releases

**Comment by danlester** [comment]
Ah, fantastic - I hadn't realized that was in place, sorry I didn't spot it...

In that case we can move to main in that repo to for day-to-day dev work and PRs.

I'll close the ticket!
